ARG HB_IMAGE_REGISTRY=docker.io
FROM ${HB_IMAGE_REGISTRY}/nginx:1
LABEL org.opencontainers.image.source=https://www.github.com/fresh2dev/myke
LABEL org.opencontainers.image.description="A dynamic Python task runner."
LABEL org.opencontainers.image.licenses=GPLv3
ARG CONTENT_PATH=public
COPY $CONTENT_PATH /usr/share/nginx/html
