#!/usr/bin/env python3
# type: ignore

import myke

# @myke.task(root=True)
# def setup():
#     ...


myke.import_module(
    "https://codeberg.org/fresh2dev/mykefiles/raw/branch/dev"
    "/src/mykefiles/hostbutter.py",
    "https://codeberg.org/fresh2dev/mykefiles/raw/branch/dev"
    "/src/mykefiles/python-package.py",
)

if __name__ == "__main__":
    myke.main(__file__)
