#!/usr/bin/env python3
# type: ignore


from time import sleep

from ppqueue import Queue

from myke import task


@task(root=True)
def setup():
    queue = Queue()
    yield queue
    queue.dispose()
    assert len(queue) == 0


@task
def hello(_relay_value: Queue):
    queue = _relay_value
    queue.put(sleep, 1)
    queue.wait()


@task
def hello_again(_relay_value: Queue):
    queue = _relay_value
    hello(queue)
    assert queue.size(finished=True) == 1
    queue.put(sleep, 1)
    assert queue.size() == 2
    queue.wait()
    assert queue.size(finished=True) == 2
