site_name: "myke"
site_description: "myke documentation"
site_url: "https://codeberg.org/fresh2dev/myke/docs"
repo_url: "https://codeberg.org/fresh2dev/myke"
repo_name: "Gitea"
edit_uri_template: "src/branch/main/{path}"
docs_dir: "../docs"
site_dir: "../public/docs"
strict: true

theme:
  name: readthedocs

## https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
# nav:
#   - Home: index.md
#   ...
